// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL7LthB1ABDlDuCQKBHPAvr9Ma48ADz-k',
    appId: '1:280525760346:web:4abdac40d22dbe2622f563',
    messagingSenderId: '280525760346',
    projectId: 'romancequotes-c784e',
    authDomain: 'romancequotes-c784e.firebaseapp.com',
    storageBucket: 'romancequotes-c784e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn_pw5q721i7NGjEY3pg8XJkLFzA2hWEQ',
    appId: '1:280525760346:android:8c44a73a6f34e17122f563',
    messagingSenderId: '280525760346',
    projectId: 'romancequotes-c784e',
    storageBucket: 'romancequotes-c784e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTwGZVW2yPzUgLb3LVjym1Xw3MSl0aZR0',
    appId: '1:280525760346:ios:7db3c00e120cbbdf22f563',
    messagingSenderId: '280525760346',
    projectId: 'romancequotes-c784e',
    storageBucket: 'romancequotes-c784e.appspot.com',
    iosBundleId: 'com.example.romanceQuotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTwGZVW2yPzUgLb3LVjym1Xw3MSl0aZR0',
    appId: '1:280525760346:ios:fe764c7979528eae22f563',
    messagingSenderId: '280525760346',
    projectId: 'romancequotes-c784e',
    storageBucket: 'romancequotes-c784e.appspot.com',
    iosBundleId: 'com.example.romanceQuotes.RunnerTests',
  );
}
